name: Setup gradle
description: setup java and gradlew
inputs:
  cmd:
    description: gradle commands to execute
    required: true
runs:
  using: composite
  steps:
    - name: Verify gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
