source "https://rubygems.org"

gem "github-pages", "~> 219", group: :jekyll_plugins

# kramdown v2 ships without the gfm parser by default. If you're using
# kramdown v1, comment out this line.
gem "kramdown-parser-gfm"